FROM python:3.11-slim
RUN apt update && apt install -y sqlite3 libsqlite3-dev

ENV PYTHONUNBUFFERED=1

WORKDIR /wpp_bot_ai

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=wpp_bot_ai/app.py

EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
